services:
  - type: worker
    name: momentreel-worker
    env: docker
    repo: https://github.com/JoaquinDW/momentreel
    branch: main
    plan: starter
    dockerfilePath: docker/worker/Dockerfile
